### ISSUE TITLE
Reminder does not update upon completion of task

### ISSUE THREAD

**Issue by jktang14** [AY2425S1-CS2103T-F14A-3/tp#119]
Reminders should account for a few factors

1. Whether a project status has been completed already or not. Currently it only looks at the closest deadline. However, upon the status of a project being changed to completed, the reminder should update to the next "in progress" task" with the closest deadline"
![image](https://github.com/user-attachments/assets/d62f79fe-9339-4d0b-9a9b-49ded527f53b)
Eg. In the above diagram, reminder should ideally show Bernice's deadline since Alex's project has already been completed
2. Account for client status. I think for this in your loop can only account for those client's with **active** client status.

**Comment by JunLongling** [comment]
Fix reminder to account only for in progress project and skip completed projects
