### ISSUE TITLE
Editing a field of a patient clears find results

### ISSUE THREAD

**Issue by jktang14** [AY2425S1-CS2103T-F14A-3/tp#122]
A feature flaw. 

After filtering the list using find. I performed editing of a client's name, I would expect that it allows me to stay on the same filtered list with the updated details, but I am brought back to the entire list again. 

CRUD operations on filtered list
1. Create: Adding a new client. (Not sure how this should work given that client added may not be matching the current find filter anyway)
2. Read: Not affected
3. Update: We want it to stay on filtered list
4. Delete: Likely should stay on filtered list

**Comment by Dinoman44** [comment]
Fixed by update to UG that pre-empts this potential flaw. See PR #156
