### ISSUE TITLE
Ambiguous keywords in UserGuide

### ISSUE THREAD

**Issue by JunLongling** [AY2425S1-CS2103T-F14A-3/tp#134]
From the user guide, it say Persons matching at least **one** keyword will be returned. However, the example that follows only shows name-based searches.

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/8d73252f-6b5f-40fa-a7f1-6d5837b65695">
This makes it ambiguous whether "keywords" refers to:
All search parameters (n/, p/, e/, t/, etc.)

Example:

Its working correctly for when both name and phone match
<img width="917" alt="Screenshot 2024-10-30 at 5 20 14 PM" src="https://github.com/user-attachments/assets/1b7c6621-231c-47d0-a4cf-4f7bf6d00d7e">
<img width="793" alt="image" src="https://github.com/user-attachments/assets/6bbec16d-0d4d-4dc6-981a-7045f887dc5d">
Not working when name match and phone does not have exact match
<img width="375" alt="image" src="https://github.com/user-attachments/assets/afad95f3-f08b-4f6a-8315-03bf938cd282">
<img width="917" alt="Screenshot 2024-10-30 at 5 25 14 PM" src="https://github.com/user-attachments/assets/13acc365-3753-4a83-b198-68b60eae8cae">

The user guide is missing important information about how finds works when using multiple parameters where some match and others don't.

Suggestion:
- The term "keyword" should be clarified or replaced with more precise terminology to avoid confusion about which search parameters it applies to.
- Show example for mixed cases where If you search n/Adam p/123 and a person: Has name "Adam" but wrong email/phone/address

**Comment by Dinoman44** [comment]
Closed by #150
