### ISSUE TITLE
[PE-D][Tester E] Typing help after opening help via task bar does show help window

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#204]
Reproduction:
1. Click on the Help menu at the task bar at the top. 
2. Alt-Tab to show the application again.
2. Type help in the command line interface

The help window will not show on the screen and stay minimized.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zzawook/ped#1

**Comment by rahula1008** [comment]
Accepted.
