### ISSUE TITLE
[PE-D][Tester E] Cannot find out, roll back, or clear current sorting scheme.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#209]
The user cannot know what is the current sorting scheme is, so once the user enters a new sorting scheme and wants to go back to previous sorting scheme, he or she does not know what sorting scheme to use. Also, it's impossible to clear current sorting scheme, nor it identifies what the default sorting order is.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zzawook/ped#4

**Comment by rahula1008** [comment]
Will just add a note to the user guide to address this.
