### ISSUE TITLE
[PE-D][Tester C] Edit flaw

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#212]
![Screenshot 2024-11-08 at 4.58.14 PM.png](https://raw.githubusercontent.com/Harithhh06/ped/main/files/4fb5e827-01cd-4be9-a98c-a57961dc4327.png)

You are able to edit fields for clients until they are all the same, even if this is prevented in the add feature

eg. 
1. copy the add for index 1
2. change phone by 1 digit
3. edit the newly added client's phone to be the same as index 1

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Harithhh06/ped#4

**Comment by rahula1008** [comment]
Ignored again, for the same reason as we ignored the other issues from this tester. He has used e@o.com and e@0.com which count as two separate emails, thus they are not duplicates.
