### ISSUE TITLE
[PE-D][Tester C] Edit flaw

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#214]
![Screenshot 2024-11-08 at 5.03.46 PM.png](https://raw.githubusercontent.com/Harithhh06/ped/main/files/c5304814-3492-4376-ad37-741c70c8ba6e.png)

Able to have 2 contacts of the same details but cannot add a third with the same

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Harithhh06/ped#5

**Comment by rahula1008** [comment]
Invalid because he doesn't actually have 2 clients with the same details, the second one he's referring to has a different email, which nds in 0.com instead of o.com.
