### ISSUE TITLE
[PE-D][Tester D] Specificity of Error Messages

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#218]
The error message is not detailed enough. The error message should be more clear if it indicates that the current input is 'invalid' with a detailed reason.

input: add n/John Dimon p/98765432 e/johnd@gmail.com a/Maxwell Street, #05-01 t/JP Morgan t/C***TO ps/in progress* py/*pending cs/active d/09-09-2024

output: Tags names should be alphanumeric and may contain spaces.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: munhuikim/ped#4

**Comment by rahula1008** [comment]
We think the error message is detailed enough because alphanumeric means that * is not allowed.
