### ISSUE TITLE
[PE-D][Tester D] Missing Hyperlinks in User Guide for Navigation and Glossary Terms

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14A-3/tp#223]
The User Guide currently lacks helpful hyperlinks that would enhance navigation. 

For example, glossary terms should link directly to their definitions in the glossary, and a "Back to Content" hyperlink should be provided to allow users to quickly return to the content page without needing to scroll to the top. Adding these links would improve the overall user experience by making it easier to navigate and reference key terms within the guide.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: munhuikim/ped#8

**Comment by rahula1008** [comment]
Will improve by adding a hyperlink in the table of contents that links to the glossary.

**Comment by Dinoman44** [comment]
Closing this issue. Reason: we do not have (and do not need) a glossary for the User Guide.
