### ISSUE TITLE
[PE-D][Tester E] Cannot delete archived user

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14A-3/tp#228]
Deleting an archived user is prohibited by the application. However, considering possible use case as a user, deleting user from archived-list, I believe, seems like a valid use case that should be supported. Although editing might be unnecessary for archived list, deleting from the list could be feature that should be allowed to the user.

![image.png](https://raw.githubusercontent.com/zzawook/ped/main/files/e2b9885f-35a0-4e23-9ec2-7a5e78af9a1b.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zzawook/ped#8

**Comment by rahula1008** [comment]
Will briefly mention this in the user guide.
