### ISSUE TITLE
[PE-D][Tester B] User Guide does not mention how tags are searched in "find" command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#230]
Under "find" command in user guide, how tag is searched is not mentioned:

![image.png](https://raw.githubusercontent.com/ChenLeiyu/ped/main/files/15faa440-d148-47e1-ba5f-66da381411c9.png)

Most other fields are mentioned but not for tag.

From testing, tags must also match the exact string and hence should be included in the first bullet point in the image above.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ChenLeiyu/ped#2

**Comment by rahula1008** [comment]
We will update the user guide to inform the user that tags must be an exact search, i.e "Morgan" will not give search results for "Morgan Stanley".
