### ISSUE TITLE
[PE-D][Tester B] Names do not accept "/" which is common in Indian names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14A-3/tp#237]
It is common for Indian names to contain "s/o" or "d/o" which is not allowed as a name in the current implementation. I believe it is reasonable for clients to have names containing "/" and thus this should be allowed to be in the name.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ChenLeiyu/ped#4

**Comment by rahula1008** [comment]
Will fix this by updating UG to show the work around to use 's o' or 'son off '
